language: node_js
sudo: false
node_js:
  - stable
  
services:

cache:
  directories:
    - node_modules

before_script: 
  - npm install -g istanbul && npm install -g mocha
script:
  - npm test 
  # Send coverage data to Coveralls
# after_script: 
#   - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

  # after_success: 'npm run coverage'
 